### ISSUE TITLE
nextjs怎么引入全局样式？

### ISSUE THREAD

**Issue by liubin915249126** [sdli/next-antd-aza-less#2]
按照你的方法，antd的less可以避免css-modules,但我现在想引入全局的样式供所有页面使用，有好的办法吗？求指导

**Comment by sdli** [comment]
> 按照你的方法，antd的less可以避免css-modules,但我现在想引入全局的样式供所有页面使用，有好的办法吗？求指导

```css

// 方法1
*{
  padding: 16px;
}

// 方法2，单个使用
:global(.your_class_name){
  padding: 16px;
}
```
